spring.application.name=sistema-loja

# ===============================
# BANCO H2 (ARQUIVO - PERSISTENTE)
# ===============================
spring.datasource.url=jdbc:h2:file:./data/meubanco;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# mostra SQL no console (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONSOLE H2 (ACESSO WEB)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# PORTA (pode deixar padrão 8080)
# ===============================
server.port=8080
